# release action with semantic release
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      # Set up our some variables for future use
      # Adapted from https://github.community/t/how-to-get-just-the-tag-name/16241/7
      # Tag name: ${{ steps.get_vars.outputs.TAG_NAME }}
      # Zip name: ${{ steps.get_vars.outputs.ZIP_NAME }}
      # Expected Release Download URL: ${{ steps.get_vars.outputs.RELEASE_DOWNLOAD_URL }}
      # Expected Release module.json URL: ${{ steps.get_vars.outputs.RELEASE_INSTALL_URL }}
      - name: Set up variables
        id: get_vars
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo "TAG_NAME=$TAG" >> $GITHUB_OUTPUT
          echo "ZIP_NAME=pf2e-xp-$TAG.zip" >> $GITHUB_OUTPUT
          echo "RELEASE_DOWNLOAD_URL=https://github.com/${{ github.repository }}/releases/download/$TAG/pf2e-xp-$TAG.zip" >> $GITHUB_OUTPUT
          echo "RELEASE_INSTALL_URL=https://github.com/${{ github.repository }}/releases/download/$TAG/module.json" >> $GITHUB_OUTPUT

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip files
        run: |
          cd dist
          zip ${{ steps.get_vars.outputs.ZIP_NAME }} -r *.mjs lang module.json templates

      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false # Set this to false if you want to prevent updating existing releases
          name: ${{ steps.get_vars.outputs.TAG_NAME }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'dist/module.json, dist/${{ steps.get_vars.outputs.ZIP_NAME }}'
          tag: ${{ steps.get_vars.outputs.TAG_NAME }}
          generateReleaseNotes: true
